/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.managerapp;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import io.socket.client.IO;
import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import java.net.URI;
import java.net.URLEncoder;
import java.util.ArrayList;
import org.json.JSONArray;
import org.json.JSONObject;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author techninza
 */
public class LeftPanel extends javax.swing.JPanel {

//    ArrayList<data> array=new ArrayList();
    /**
     * Creates new form LeftPanel
     */
    public LeftPanel() {
        initComponents();
        tabledata();

//        mythread my=new mythread();
//        my.start();
    }

    private void tabledata() {
        Object[][] data = {
            //            {"John Doe", "john.doe@example.com", 32},
            //            {"Jane Doe", "jane.doe@example.com", 28},
            //            {"Peter Jones", "peter.jones@example.com", 40},
            {"Coffee", 180.50, 180.50},
            {"Corn", 492.19, 473.07},
            {"Cotton", 78.27, 78.67},
            {"Soybean", 1359.38, 1358.39},
            {"Sugar", 27.03, 27.21},
            {"Wheet", 0.3870, 0.3890},
            {"AdAUSD", 80.96, 85.96},
            {"BCHUSD", 226.230, 227.200},
            {"BNBUSD", 257.700, 258.900},
            {"Copart", 1836.35, 1836.25},
            {"Vodafone", 0.7455, 0.7455},
            {"ACC#", 1836.35, 1836.35},
            {"ALCOA", 27.08, 27.21},
            {"AUDCAD", 27.08, 27.21},
            {"AUDCARD.v", 0.90167, 0.90176},
            {"AUDCHF", 0.58039, 0.58043},
            {"AUDCHF.u", 0.58039, 0.58043}
        };

        // Create the column names for the table
        String[] columnNames = {"Symbol", "Bid", "Ask"};

        // Create the table model
        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);

        JTable jTable1 = new JTable(tableModel);
        setLayout(new BorderLayout());
        JScrollPane scrollPane = new JScrollPane(jTable1);
        add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
