/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.managerapp;

import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kapil
 */
public class MarginCalls extends javax.swing.JPanel {

    /**
     * Creates new form MarginCalls
     */
    public MarginCalls() {
        initComponents();
        table();
    }

    void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Login");
        model.addColumn("Level");

        for (int i = 0; i < 10; i++) {
            String rowData[] = {"181.34", "39%"};
            model.addRow(rowData);
        }

        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Details");
        JMenuItem menuItem2 = new JMenuItem("Email");
        JMenuItem menuItem3 = new JMenuItem("Auto Arrange");
        JMenuItem menuItem4 = new JMenuItem("Grid");
        JMenuItem menuItem5 = new JMenuItem("Header");

        popupMenu.add(menuItem1);
        popupMenu.add(menuItem2);
        popupMenu.addSeparator();
        popupMenu.add(menuItem3);
        popupMenu.add(menuItem4);
        popupMenu.add(menuItem5);

        JTable jt = new JTable();
        JScrollPane jsp = new JScrollPane(jt);
        setLayout(new BorderLayout());
        jt.setEnabled(false);
        jt.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    // Show the popup menu
                    popupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
        add(jsp, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
