/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.managerapp;

import java.awt.BorderLayout;
import javax.swing.JSplitPane;

/**
 *
 * @author kapilrohilla
 */
public class SpecificationPanel extends javax.swing.JPanel {

    /**
     * Creates new form SpecificationPanel
     */
    public SpecificationPanel() {
        framesetup();
    }

    private void framesetup() {

        SpecificationLeftPanel leftPanel = new SpecificationLeftPanel();
        SpecificationRightPanel rightPanel = new SpecificationRightPanel();
        SpecificationBottom bottomPanel = new SpecificationBottom();
        JSplitPane jSplitpanetop = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, leftPanel, rightPanel);

        JSplitPane jSplitpaneScreen = new JSplitPane(JSplitPane.VERTICAL_SPLIT, jSplitpanetop, bottomPanel);

        setLayout(new BorderLayout());
//        add(jSplitpane,BorderLayout.CENTER );
        add(jSplitpaneScreen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
