/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.managerapp;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kapil
 */
public class TradeServerBottom extends javax.swing.JPanel {

    /**
     * Creates new form TradeServerBottom
     */
    public TradeServerBottom() {
        initComponents();
        table();
    }

    final void table() {
        DefaultTableModel model = new DefaultTableModel();
        String[] columns = {"Login", "Symbol", "Type", "Volume", "Price", "S / L", "T / P", "Price", "Profit"};

        for (String column : columns) {
            model.addColumn(column);
        }
        for (int i = 0; i < 5; i++) {
            String[] rowData = {"128384", "audnzd", "sell limit", "1.01/ 0.00", "1.09646", "0.0000", "1.09525", "placed"};
            model.addRow(rowData);
        }
        JTable jt = new JTable(model);
        JScrollPane jsp = new JScrollPane(jt);
        setLayout(new BorderLayout());
        add(jsp, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
